# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(282, 191)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.ckbLetter = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ckbLetter.setFont(font)
        self.ckbLetter.setChecked(True)
        self.ckbLetter.setObjectName("ckbLetter")
        self.gridLayout.addWidget(self.ckbLetter, 1, 0, 1, 1)
        self.ckbNumber = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ckbNumber.setFont(font)
        self.ckbNumber.setChecked(True)
        self.ckbNumber.setObjectName("ckbNumber")
        self.gridLayout.addWidget(self.ckbNumber, 2, 0, 1, 1)
        self.ckbSpecialChar = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ckbSpecialChar.setFont(font)
        self.ckbSpecialChar.setChecked(True)
        self.ckbSpecialChar.setObjectName("ckbSpecialChar")
        self.gridLayout.addWidget(self.ckbSpecialChar, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.spbCharNumber = QtWidgets.QSpinBox(Dialog)
        self.spbCharNumber.setMinimum(4)
        self.spbCharNumber.setProperty("value", 15)
        self.spbCharNumber.setObjectName("spbCharNumber")
        self.gridLayout.addWidget(self.spbCharNumber, 4, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Configurações"))
        self.label.setText(_translate("Dialog", "A sua senha deve conter:"))
        self.ckbLetter.setText(_translate("Dialog", "Letras"))
        self.ckbNumber.setText(_translate("Dialog", "Números"))
        self.ckbSpecialChar.setText(_translate("Dialog", "Caracteres especiais"))
        self.label_2.setText(_translate("Dialog", "Quantidade de caracteres:"))
