# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 348)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background: white")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 448, 157))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelOutput = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOutput.setFont(font)
        self.labelOutput.setText("")
        self.labelOutput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelOutput.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelOutput.setObjectName("labelOutput")
        self.gridLayout_2.addWidget(self.labelOutput, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 6, 0, 1, 3)
        self.btnMostrarSenha = QtWidgets.QPushButton(self.centralwidget)
        self.btnMostrarSenha.setObjectName("btnMostrarSenha")
        self.gridLayout.addWidget(self.btnMostrarSenha, 0, 0, 1, 1)
        self.btnAlterarSenha = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlterarSenha.setObjectName("btnAlterarSenha")
        self.gridLayout.addWidget(self.btnAlterarSenha, 3, 0, 1, 1)
        self.btnExcluirSenha = QtWidgets.QPushButton(self.centralwidget)
        self.btnExcluirSenha.setObjectName("btnExcluirSenha")
        self.gridLayout.addWidget(self.btnExcluirSenha, 4, 0, 1, 1)
        self.btnCadastrarSenha = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrarSenha.setObjectName("btnCadastrarSenha")
        self.gridLayout.addWidget(self.btnCadastrarSenha, 2, 0, 1, 1)
        self.btnMostrarApps = QtWidgets.QPushButton(self.centralwidget)
        self.btnMostrarApps.setObjectName("btnMostrarApps")
        self.gridLayout.addWidget(self.btnMostrarApps, 1, 0, 1, 1)
        self.labelInstrunction = QtWidgets.QLabel(self.centralwidget)
        self.labelInstrunction.setText("")
        self.labelInstrunction.setObjectName("labelInstrunction")
        self.gridLayout.addWidget(self.labelInstrunction, 0, 2, 1, 1)
        self.btnTool = QtWidgets.QToolButton(self.centralwidget)
        self.btnTool.setObjectName("btnTool")
        self.gridLayout.addWidget(self.btnTool, 2, 1, 1, 1)
        self.inputUser = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputUser.setFont(font)
        self.inputUser.setObjectName("inputUser")
        self.gridLayout.addWidget(self.inputUser, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Generator"))
        self.btnMostrarSenha.setText(_translate("MainWindow", "Mostrar uma senha"))
        self.btnAlterarSenha.setText(_translate("MainWindow", "Alterar uma senha"))
        self.btnExcluirSenha.setText(_translate("MainWindow", "Excluir uma senha"))
        self.btnCadastrarSenha.setText(_translate("MainWindow", "Cadastrar uma nova senha"))
        self.btnMostrarApps.setText(_translate("MainWindow", "Mostrar Apps/Sites"))
        self.btnTool.setText(_translate("MainWindow", "..."))
